FROM gcc:11.2.0 AS builder
WORKDIR /usr/connectlib
RUN apt update && apt install build-essential -y
ADD . /usr/connectlib

FROM builder
WORKDIR /usr/connectlib
RUN make clean && make pong

FROM debian:bookworm-slim
WORKDIR /root/
COPY --from=1 /usr/connectlib/pong /root/pong
CMD ["/root/pong", "12345", "TCP"]